#pipeline name/workflow name
name: First workflow
#set trigger
on:
push:
branches:
        - main
jobs:
     print-message:
     runs-on: ubuntu-latest

     steps:
     #step1
      name: print welcome message
      run: echo'welcom to github action'
     #step2:
      name: print Hello message
      run: echo'Hello...'