name: First workflow
on:
 push:
    branches:
        - main

jobs:
        print-message:
        runs-on: ubuntu-latest
        steps:
        - name: print welcom message
          run: echo "welcome to github action"

        - name: print Hello message
          run: echo "Hello...."
